apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    app.kubernetes.io/name: recon-web
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{- if .Values.auth.token }}
  AUTH_TOKEN: {{ .Values.auth.token | quote }}
  {{- end }}
  {{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.notifications.telegram.botToken }}
  TELEGRAM_BOT_TOKEN: {{ .Values.notifications.telegram.botToken | quote }}
  {{- end }}
  {{- if .Values.notifications.email.smtpUser }}
  SMTP_USER: {{ .Values.notifications.email.smtpUser | quote }}
  SMTP_PASS: {{ .Values.notifications.email.smtpPass | quote }}
  {{- end }}
