apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app.kubernetes.io/name: recon-web
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: recon-web
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: {{ .Release.Name }}
