/**
 * Hardcoded map of TLDs to their WHOIS servers.
 * Sourced from IANA root zone database knowledge.
 */
export const WHOIS_SERVERS: Record<string, string> = {
  // Generic TLDs
  com: 'whois.verisign-grs.com',
  net: 'whois.verisign-grs.com',
  org: 'whois.pir.org',
  info: 'whois.afilias.net',
  biz: 'whois.biz',
  name: 'whois.nic.name',
  pro: 'whois.registrypro.pro',
  mobi: 'whois.dotmobiregistry.net',
  tel: 'whois.nic.tel',
  asia: 'whois.nic.asia',
  cat: 'whois.nic.cat',
  jobs: 'whois.nic.jobs',
  travel: 'whois.nic.travel',
  museum: 'whois.museum',
  coop: 'whois.nic.coop',
  aero: 'whois.aero',
  post: 'whois.dotpostregistry.net',
  xxx: 'whois.nic.xxx',

  // New gTLDs (popular)
  io: 'whois.nic.io',
  dev: 'whois.nic.google',
  app: 'whois.nic.google',
  page: 'whois.nic.google',
  new: 'whois.nic.google',
  how: 'whois.nic.google',
  soy: 'whois.nic.google',
  day: 'whois.nic.google',
  ai: 'whois.nic.ai',
  co: 'whois.nic.co',
  me: 'whois.nic.me',
  tv: 'whois.nic.tv',
  cc: 'ccwhois.verisign-grs.com',
  ws: 'whois.website.ws',
  fm: 'whois.nic.fm',
  am: 'whois.amnic.net',
  la: 'whois.nic.la',
  gg: 'whois.gg',
  je: 'whois.je',
  im: 'whois.nic.im',
  sh: 'whois.nic.sh',
  ac: 'whois.nic.ac',
  cx: 'whois.nic.cx',
  nu: 'whois.iis.nu',
  sc: 'whois.nic.sc',
  to: 'whois.tonic.to',
  tk: 'whois.dot.tk',
  pw: 'whois.nic.pw',
  club: 'whois.nic.club',
  xyz: 'whois.nic.xyz',
  online: 'whois.nic.online',
  site: 'whois.nic.site',
  store: 'whois.nic.store',
  tech: 'whois.nic.tech',
  space: 'whois.nic.space',
  fun: 'whois.nic.fun',
  icu: 'whois.nic.icu',
  top: 'whois.nic.top',
  vip: 'whois.nic.vip',
  wang: 'whois.gtld.knet.cn',
  shop: 'whois.nic.shop',
  blog: 'whois.nic.blog',
  cloud: 'whois.nic.cloud',
  live: 'whois.nic.live',
  work: 'whois.nic.work',

  // European ccTLDs
  uk: 'whois.nic.uk',
  de: 'whois.denic.de',
  fr: 'whois.nic.fr',
  nl: 'whois.sidn.nl',
  it: 'whois.nic.it',
  es: 'whois.nic.es',
  pt: 'whois.dns.pt',
  be: 'whois.dns.be',
  at: 'whois.nic.at',
  ch: 'whois.nic.ch',
  li: 'whois.nic.li',
  dk: 'whois.dk-hostmaster.dk',
  se: 'whois.iis.se',
  no: 'whois.norid.no',
  fi: 'whois.fi',
  ie: 'whois.weare.ie',
  cz: 'whois.nic.cz',
  sk: 'whois.sk-nic.sk',
  pl: 'whois.dns.pl',
  hu: 'whois.nic.hu',
  ro: 'whois.rotld.ro',
  bg: 'whois.register.bg',
  hr: 'whois.dns.hr',
  rs: 'whois.rnids.rs',
  si: 'whois.register.si',
  ee: 'whois.tld.ee',
  lv: 'whois.nic.lv',
  lt: 'whois.domreg.lt',
  ua: 'whois.ua',
  ru: 'whois.tcinet.ru',
  su: 'whois.tcinet.ru',
  eu: 'whois.eu',
  lu: 'whois.dns.lu',
  is: 'whois.isnic.is',
  gr: 'whois.ripe.net',
  tr: 'whois.trabis.gov.tr',
  mt: 'whois.nic.org.mt',
  md: 'whois.nic.md',
  by: 'whois.cctld.by',
  ge: 'whois.registration.ge',
  al: 'whois.ripe.net',
  ba: 'whois.ripe.net',
  mk: 'whois.marnet.mk',

  // Asia-Pacific ccTLDs
  jp: 'whois.jprs.jp',
  cn: 'whois.cnnic.cn',
  kr: 'whois.kr',
  tw: 'whois.twnic.net.tw',
  hk: 'whois.hkirc.hk',
  sg: 'whois.sgnic.sg',
  my: 'whois.mynic.my',
  th: 'whois.thnic.co.th',
  id: 'whois.id',
  ph: 'whois.dot.ph',
  vn: 'whois.vnnic.vn',
  in: 'whois.registry.in',
  pk: 'whois.pknic.net.pk',
  bd: 'whois.btcl.net.bd',
  nz: 'whois.srs.net.nz',
  au: 'whois.auda.org.au',
  mn: 'whois.nic.mn',
  kz: 'whois.nic.kz',
  uz: 'whois.cctld.uz',

  // Americas ccTLDs
  us: 'whois.nic.us',
  ca: 'whois.cira.ca',
  mx: 'whois.mx',
  br: 'whois.registro.br',
  ar: 'whois.nic.ar',
  cl: 'whois.nic.cl',
  pe: 'whois.nic.pe',
  ve: 'whois.nic.ve',
  ec: 'whois.nic.ec',
  uy: 'whois.nic.org.uy',
  bo: 'whois.nic.bo',
  py: 'whois.nic.py',
  tt: 'whois.nic.tt',

  // Africa & Middle East ccTLDs
  za: 'whois.registry.net.za',
  ng: 'whois.nic.net.ng',
  ke: 'whois.kenic.or.ke',
  tz: 'whois.tznic.or.tz',
  gh: 'whois.nic.gh',
  il: 'whois.isoc.org.il',
  sa: 'whois.nic.net.sa',
  ae: 'whois.aeda.net.ae',
  qa: 'whois.registry.qa',
  om: 'whois.registry.om',
  ir: 'whois.nic.ir',
  ma: 'whois.registre.ma',
  tn: 'whois.ati.tn',

  // Multi-part second-level TLDs (key = second-level.tld)
  'co.uk': 'whois.nic.uk',
  'org.uk': 'whois.nic.uk',
  'me.uk': 'whois.nic.uk',
  'net.uk': 'whois.nic.uk',
  'ac.uk': 'whois.nic.uk',
  'gov.uk': 'whois.nic.uk',
  'co.jp': 'whois.jprs.jp',
  'ne.jp': 'whois.jprs.jp',
  'or.jp': 'whois.jprs.jp',
  'ac.jp': 'whois.jprs.jp',
  'go.jp': 'whois.jprs.jp',
  'com.au': 'whois.auda.org.au',
  'net.au': 'whois.auda.org.au',
  'org.au': 'whois.auda.org.au',
  'com.br': 'whois.registro.br',
  'net.br': 'whois.registro.br',
  'org.br': 'whois.registro.br',
  'com.cn': 'whois.cnnic.cn',
  'net.cn': 'whois.cnnic.cn',
  'org.cn': 'whois.cnnic.cn',
  'com.tw': 'whois.twnic.net.tw',
  'org.tw': 'whois.twnic.net.tw',
  'com.hk': 'whois.hkirc.hk',
  'org.hk': 'whois.hkirc.hk',
  'co.nz': 'whois.srs.net.nz',
  'net.nz': 'whois.srs.net.nz',
  'org.nz': 'whois.srs.net.nz',
  'co.za': 'whois.registry.net.za',
  'org.za': 'whois.registry.net.za',
  'net.za': 'whois.registry.net.za',
  'co.in': 'whois.registry.in',
  'net.in': 'whois.registry.in',
  'org.in': 'whois.registry.in',
  'com.mx': 'whois.mx',
  'org.mx': 'whois.mx',
  'com.ar': 'whois.nic.ar',
  'org.ar': 'whois.nic.ar',
  'com.co': 'whois.nic.co',
  'net.co': 'whois.nic.co',
  'com.hr': 'whois.dns.hr',
  'com.sg': 'whois.sgnic.sg',
  'com.my': 'whois.mynic.my',
  'co.kr': 'whois.kr',
  'or.kr': 'whois.kr',
  'co.id': 'whois.id',
  'web.id': 'whois.id',
  'com.tr': 'whois.trabis.gov.tr',
  'org.tr': 'whois.trabis.gov.tr',
  'com.ua': 'whois.ua',
  'co.il': 'whois.isoc.org.il',
  'org.il': 'whois.isoc.org.il',
  'com.pk': 'whois.pknic.net.pk',
  'org.pk': 'whois.pknic.net.pk',
  'com.pe': 'whois.nic.pe',
  'org.pe': 'whois.nic.pe',
  'com.ng': 'whois.nic.net.ng',
  'org.ng': 'whois.nic.net.ng',
};

/**
 * Look up the WHOIS server for a given TLD or multi-part TLD.
 * Tries multi-part first (e.g. "co.uk"), then falls back to plain TLD (e.g. "uk").
 * Returns undefined if no mapping is found.
 */
export function getWhoisServer(tld: string): string | undefined {
  const normalized = tld.toLowerCase();
  return WHOIS_SERVERS[normalized];
}
